### ISSUE TITLE
BUG: selection host connection timeout.

### ISSUE THREAD

**Issue by ericvlog** [TimerErTim/downlomatic#24]
**Description**

**Reproduction**
1. install the app on windows 10
2. report virus, close antivirus, continue install
3. after install click open.
4. selection host, connection timeout.

windows 10 pro
![image](https://user-images.githubusercontent.com/64370408/190980102-532a6afc-ebaf-4f07-afff-23d30e90a7fc.png)

**Comment by TimerErTim** [comment]
Hello!

I recently changed the domain entry for "timerertim.eu". Meaning, the server is not reachable anymore. I will have to change the default server in the code and make a new release.

Because I currently don't have much time on my hands, here is a temporary workaround for you:

1. Locate where the binary is installed to
2. Run the binary with cmd using `<path-to-binary> --server server.timerertim.eu`

If any other problem occurs, please let me know. Thanks for submitting this bug report!
